# Generated by Django 4.0.1 on 2022-01-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('yoe', models.PositiveSmallIntegerField()),
                ('tool_1', models.CharField(max_length=20)),
                ('tool_2', models.CharField(blank=True, max_length=20, null=True)),
                ('tool_3', models.CharField(blank=True, max_length=20, null=True)),
                ('salary', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=30, unique=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.industry')),
            ],
        ),
    ]
