# Generated by Django 4.0.1 on 2022-02-10 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_common_user',
        ),
    ]
