# Generated by Django 4.0.1 on 2022-01-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_industry_salaryblog_alter_customuser_options_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name': 'Industy', 'verbose_name_plural': 'Industries'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='salaryblog',
            options={'verbose_name': 'Salary Info', 'verbose_name_plural': 'Salary Info'},
        ),
    ]
