# Generated by Django 4.0.1 on 2022-02-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_is_common_user_customuser_is_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='user.png', upload_to='media/images/'),
        ),
    ]
