# Generated by Django 4.0.1 on 2022-01-26 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_industry_options_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryblog',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.job'),
            preserve_default=False,
        ),
    ]
