# Generated by Django 4.0.1 on 2022-01-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_salaryblog_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryblog',
            name='location',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
