# Generated by Django 4.0.1 on 2022-01-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Industy',
                'verbose_name_plural': 'Industries',
            },
        ),
    ]
